#+title: Freebsd点滴积累
#+OPTIONS: toc:t num:t

* 安装Freebsd
  官网地址：[[https://www.freebsd.org]]

  当前的release版是13.1：
   [[https://www.freebsd.org/where/][file:images/13.1_freebsd.jpg]]

  如上图所示，下载memstick版，然后写入u盘(可用baleanEtcher工具)，生成u盘启动盘。

  翻出一台废旧的笔记本，型号：ThinkPad SL410K, 2007年购入，15个年头了，看看能否顺利装上freebsd。

  u盘顺利启动，启动菜单出现,默认第一项"1 Boot Multi user"进行安装

  感觉，安装过程，似乎比以前的版本快了许多，有两个重点要关注：
  - 文件系统选择: 选zfs，这是freebsd的特色
  - 网络设置: 作为服务器，设一个固定地址. 也可以在安装完后，使用命令：bsdconfig 进入设置程序。
      
  安装过程比想象中顺利，重启，进入登录命令行

  15年前的笔记本，仍可以顺利安装并运行最新版的freebsd 13.1，欣喜。

  让我们看看笔记本的物理内存：
  #+BEGIN_EXAMPLE
  cat /var/run/dmesg.boot | grep memory
  #+END_EXAMPLE
  查得，该笔记本物理内存为:2048MB。

  令人惊叹，估计也就是freebsd这样的服务器操作系统能跑起来。这也是学习freebsd的一个重要理由！

* 初始设置
** 科学上网
   先解决科学上网的问题，否则，相关的资源访问会令人痛不欲生。

   科学上网，也是开发工作必备之技能。

   这里需要掌握软路由的相关技能，具体安装及设置，另起文档详述。
** 安装Emacs
   默认的文字编辑工具是vi，这个比较反人类，所以，第一时间需要安装编辑文档的神器：emacs

   使用pkg安装emacs:
   #+begin_example 
     pkg upgrade #将已安装的软件包升级到最新版本
     pkg update  #更新pkg源目录
     pkg search emacs-nox #查找源目录中emacs-nox的相关信息
     pkg install emacs-nox #emacs-nox表示无图形界面的版本
   #+end_example

   emacs也是写代码的神器，建议掌握。

   查看下emacs的安装情况
   #+BEGIN_SRC shell
     which emacs
   #+END_SRC
   返回：
   #+BEGIN_EXAMPLE
   /usr/local/bin/emacs
   #+END_EXAMPLE
   
** ports系统的安装
   由于默认是最小安装，没有安装ports系统
   #+begin_example
     cd /usr/ports
     ls
     该目录应是空的，表明ports系统尚未安装
   #+end_example
   首次操作，需要执行以下操作
   #+begin_example
     portsnap fetch extract #从源服务器中抓取并解压到/usr/ports目录中
   #+end_example
   以后更新ports，则执行以下操作
   #+begin_example
     portsnap fetch update #抓取并更新
   #+end_example
   出于学习的目的，以后有些小软件，可以用ports系统编译安装；对于大软件，比如emacs-nox等，还是用pkg安装二进制文件，省事儿！

   笔记的目标：记录关键点，掌握核心操作要领，更为复杂的操作指令都可以在网上查到，以后用到时，再补充进笔记中。
   refreshing...
